In [1]:
import numpy as np
from dataunload import X_train,Y_train,X_test,Y_test
import random



2000
2000
6
2
before reshaping 

X_train  (6, 64, 64, 3)
X_test  (2, 64, 64, 3)
Y_train  (6,)
Y_test  (2,)
X_train  (12288, 6)
X_test  (12288, 2)
Y_train  (1, 6)
Y_test  (1, 2)


In [2]:
#initializing parameters w and b
w = np.random.randn(12288,5)
b = np.zeros((5,1))
print(w.shape)
print(b.shape)

(12288, 5)
(5, 1)


In [3]:

z = np.dot(w.T, X_train) + b
z

array([[ -1.13435744,  13.93083966,   3.2257081 , -31.77884622,
         20.89105054, -15.39345187],
       [-25.56496371, -25.60082962,  -4.89844646, -18.49165993,
        -49.87784888, -66.75735424],
       [-93.03500047, -34.30958729, -97.8485976 , -27.22461457,
        -64.33427944, -28.56862424],
       [ 68.05396109,   8.78708234,  71.18405497,  37.42226506,
         28.73309472,  48.87185538],
       [-32.58485083,  -9.10005067, -93.1444689 , -72.46676269,
        -39.15031055, -75.75256975]])

In [4]:
def sigmoid(z):
    return 1/(1 + np.exp(-z))     

In [5]:
A = sigmoid(z)
A

array([[2.43357848e-01, 9.99999109e-01, 9.61790339e-01, 1.57987397e-14,
        9.99999999e-01, 2.06399531e-07],
       [7.89364026e-12, 7.61554458e-12, 7.40294827e-03, 9.31481268e-09,
        2.17934237e-22, 1.01776948e-29],
       [3.93924211e-41, 1.25757983e-15, 3.19811445e-43, 1.50141283e-12,
        1.14809398e-28, 3.91565243e-13],
       [1.00000000e+00, 9.99847330e-01, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00],
       [7.05633340e-15, 1.11647684e-04, 3.53078389e-41, 3.37353208e-32,
        9.93656234e-18, 1.26205118e-33]])

In [6]:
def cost_fun(y, y_hat):
    m = y.shape[1]
    # actual_value = y
    # predicted_value = y_hat
     
    return - (np.dot(y, np.log(y_hat).T) + np.dot((1 - y), np.log(1 - y_hat).T)) / m

In [7]:
cost = cost_fun(Y_train, A)
cost

C:\Users\JEET\AppData\Local\Temp\ipykernel_4824\913632505.py:6: RuntimeWarning: divide by zero encountered in log
  return - (np.dot(y, np.log(y_hat).T) + np.dot((1 - y), np.log(1 - y_hat).T)) / m


array([[ 9.55796451, 11.61081396, 25.76153372,         nan, 19.02529597]])

In [8]:
m = Y_train.shape[1]
dw = (np.dot(X_train,(A - Y_train).T ))/m
db = np.sum((A - Y_train))/m

dw.shape

(12288, 5)

In [206]:
learning_rate = 0.0001
w -= learning_rate*dw
b -= learning_rate*db
#

In [207]:
z = np.dot(w.T, X_train) + b

In [208]:
A = sigmoid(z)
print(A)

[[1.00000000e+00 1.00000000e+00 1.00000000e+00 1.00000000e+00
  1.00000000e+00 1.00000000e+00 1.00000000e+00 8.31395901e-09]
 [1.00000000e+00 6.13704508e-08 1.00000000e+00 1.00000000e+00
  9.99999254e-01 1.00000000e+00 9.99999999e-01 1.00000000e+00]
 [9.99999894e-01 9.71001804e-13 1.22583767e-17 1.00000000e+00
  1.52593095e-13 4.14319849e-01 1.50429663e-19 4.81924948e-03]
 [9.99999972e-01 7.00877125e-15 2.10093653e-05 6.68428738e-18
  2.91253161e-03 3.20884384e-15 2.36730613e-04 5.81760518e-07]
 [3.15448909e-73 5.20760105e-37 3.31911651e-70 1.13696520e-42
  9.27773470e-42 1.22873357e-80 9.24376922e-57 1.01465633e-45]]


In [209]:
cost = cost_fun(Y_train, A)
print(cost)

[[        nan         nan         inf 13.25627339 62.52144154]]


C:\Users\JEET\AppData\Local\Temp\ipykernel_1144\2546458613.py:6: RuntimeWarning: divide by zero encountered in log
  return - (np.dot(y, np.log(y_hat).T) + np.dot((1 - y), np.log(1 - y_hat).T)) / m


In [210]:
def optimize(num_iteration,A,w,b):

    costs = []

    for i in range(num_iteration):
        
        dw = (np.dot(X_train,(A - Y_train).T ))/m
        db = np.sum((A - Y_train))/m

        w -= learning_rate*dw
        b -= learning_rate*db

        z = np.dot(w.T, X_train) + b

        A = sigmoid(z)

        cost = cost_fun(Y_train, A)
        costs.append(cost)

    return costs



    
 

In [211]:
final_costs = optimize(100,A,w,b)

C:\Users\JEET\AppData\Local\Temp\ipykernel_1144\2546458613.py:6: RuntimeWarning: divide by zero encountered in log
  return - (np.dot(y, np.log(y_hat).T) + np.dot((1 - y), np.log(1 - y_hat).T)) / m


In [223]:
final_costs[-1]
print((w[:, 0]))
print(b)


[ 0.24944222 -1.20811928 -1.50997988 ...  1.44912376 -0.41909818
 -1.57249217]
[[0.00260021]
 [0.00260021]
 [0.00260021]
 [0.00260021]
 [0.00260021]]
(12288, 5)
(5, 1)


In [228]:
print(w.shape)
print(X_train.shape)
print(b.shape)
print(z.shape)
print(A.shape)

(12288, 5)
(12288, 8)
(5, 1)
(5, 8)
(5, 8)


In [231]:
print(w)
print(b)
print(z)

[[ 0.24944222  1.22129933 -0.54173008 -2.56349444 -1.24786944]
 [-1.20811928 -0.42981509 -0.41595621  2.73640204  1.8388529 ]
 [-1.50997988  0.63611512  1.34392349  0.69831229  0.48625379]
 ...
 [ 1.44912376 -2.25711267 -0.35990558 -0.1462906  -0.06922479]
 [-0.41909818 -2.25341736 -0.45711797 -0.53356378 -0.31789447]
 [-1.57249217 -1.06787479  1.48355598 -0.16868388 -0.76095283]]
[[0.00260021]
 [0.00260021]
 [0.00260021]
 [0.00260021]
 [0.00260021]]
[[ 118.84747275   45.17649004   86.28694573   81.31897498   56.45583839
    98.86858457   55.8632095   -18.60532992]
 [  54.02380559  -16.60633731   27.32434049   53.89458392   14.1082143
    84.69289049   21.01595733   43.42067488]
 [  16.0603719   -27.66044807  -38.94032215   42.56396427  -29.51100153
    -0.34613556  -43.34079133   -5.33030617]
 [  17.37697494  -32.59161399  -10.77052124  -39.54677207   -5.83581583
   -33.3728657    -8.34835096  -14.35720637]
 [-166.93988524  -83.54552914 -159.98125787  -96.5802113   -94.48095649
  -184